spring:
  application:
    name: micro2

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

test:
  message:
    testresponse: test response from micro2