spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/KonstantinKotov/Microservices.git
          username: kotovk2109@gmail.com
          password: GithubP@ss44

server:
  port: 8888
